### ISSUE TITLE
OTP gets copied but no window gets displayed

### ISSUE THREAD

**Issue by deepesh-agarwal** [SoFriendly/2fhey#1]
OTP gets copied but no window gets displayed, the windows sometimes only appear during next reboot with the last code. Also, how to add templates?

**Comment by itsthisjustin** [comment]
Hmm that's strange. What version of macOS are you on? Any other "always on top" apps that might be interfering with it?

**Comment by itsthisjustin** [comment]
Haven't been able to figure this one out yet but please give the latest update a try and see if it's still an issue.

**Comment by deepesh-agarwal** [comment]
Where to get the latest version compiled app ?

**Comment by itsthisjustin** [comment]
You should have gotten a notification from Gumroad but otherwise check your account there
