### ISSUE TITLE
Poppup is showing in the wrong coordinates

### ISSUE THREAD

**Issue by danhp** [SoFriendly/2fhey#10]
Using chrome on Monterey (21F79) on the recent MacBook Pro.
Popup is showing in the wrong coordinates and behind the Chrome window.
![wrong_coordinates](https://user-images.githubusercontent.com/3745612/177053239-bcf47cae-dd7d-4f01-97e9-c043b1a5b4f5.png)

**Comment by TheGreatJoules** [comment]
I have the same issue regarding the position of the pop with the same build.
