### ISSUE TITLE
Regarding updates and support

### ISSUE THREAD

**Issue by TheGreatJoules** [SoFriendly/2fhey#11]
Hey 2fhey team,

Big fan of your autofill application, improves my workflow and a game changer 🙌! 
However I did have a question regarding future updates and features.
I noticed on your site it mentioned.
```
No we currently don't support automatic updates. However 2FHey was built specifically to work from a remote code recognition list so that it doesn't need to be updated as often.
```
So I'm wondering how future support will be handled moving forward.
Will a new update be available on our gumroad library?
or will an integrated update service be something in the works for this application.

**Comment by itsthisjustin** [comment]
Right now I'm just pushing new updates to Gumroad. Auto update is low on the priority list but I might get to it at some point.

**Comment by moonxkang** [comment]
hey, so a silly question -- everytime an update is pushed, we gotta go back to Gumroad and re-download the file? @itsthisjustin ty!

**Comment by itsthisjustin** [comment]
If it's a functional update like new features then yes I'll send an email out and you can grab an updated app. If it's just for support of new 2fa codes then you just have to quit and restart the app as that is fetched remote from GitHub.
