### ISSUE TITLE
Does not sync with a Twitter Code

### ISSUE THREAD

**Issue by klippas-rob** [SoFriendly/2fhey#15]
On macOS when I receive a code from Twitter in the form:
`Twitter login code: 851324442`

2FHey does not sync when the code arrives in Messages.
I click Resync and 2FHey does not detect the code.

![CleanShot 2022-09-11 at 15 01 16](https://user-images.githubusercontent.com/64809973/189705874-d03062b7-e922-4b73-8d5a-a0b6795fb534.gif)

**Comment by itsthisjustin** [comment]
I use Twitter all the time with 2FHey. Are you on the latest version of the app? I will say my twitter codes aren't remotely that long. What country are you in?

**Comment by klippas-rob** [comment]
Hi Justin,

I am on version 1.0.1.
I’m in Canada.

Cheers,
Rob

**Comment by itsthisjustin** [comment]
Fixed in the latest update! Sorry this took an absurd amount of time. Please restart and launch the app to download the latest parsing config.
