### ISSUE TITLE
Just curious, why was 2fhey forked from ohtipi?

### ISSUE THREAD

**Issue by adamfeldman** [SoFriendly/2fhey#2]
Just curious, why was [2fhey](https://github.com/SoFriendly/2fhey) forked from [ohtipi](https://github.com/Yac-Team/ohtipi) into this new repo? 

[SoFriendly](https://github.com/SoFriendly) _[appears](https://www.sofriendly.com/project/yac)_ affiliated somehow with [Yac-team](https://github.com/Yac-Team) but it's unclear. 

A short answer would be helpful for more comfort granting full disk permissions. Thank you and love the app!

**Comment by itsthisjustin** [comment]
@adamfeldman cannot believe I missed this comment, so sorry. The original app relied on a 3rd party repo that didn't seem to be getting any updates and was preventing Ohtipi from ever working on Monterey. Instead of forking it, it's a complete re-write in native code which puts it at a much smaller memory and storage footprint as well.

**Comment by itsthisjustin** [comment]
Oh also to add on to this I'm one of the founders of Yac

**Comment by adamfeldman** [comment]
No worries! Awesome, thank you for the background!

**Comment by adamfeldman** [comment]
It'd be cool if 2fhey eventually made it into Setapp – I think that's where I first found ohtipi.

**Comment by itsthisjustin** [comment]
Yep plan to at some point! Need to get a new account with them and then integrate but it'll eventually happen.

**Comment by rahul286** [comment]
I came here when I noticed https://ohtipi.com/ is redirecting to https://2fhey.com/

Is https://ohtipi.com/ being deprecated in favor of https://2fhey.com/ ? 

Just curious. I prefer native apps over node.js apps so no complaint.

**Comment by itsthisjustin** [comment]
Yep correct. The existing infrastructure on the old app stopped working on newer macOS versions. Was easier to just rebuild it.
