### ISSUE TITLE
Popup does not overlay on top of Microsoft Edge

### ISSUE THREAD

**Issue by donutshredda** [SoFriendly/2fhey#24]
M1 2020 Macbook Pro, overlay of popup does not display on top of Microsoft Edge. I can still paste as normal but the popup is not visable.

**Comment by itsthisjustin** [comment]
Will see if I can reproduce. You're not using an external display correct?

**Comment by shreddeddonut** [comment]
It's the same on external display and on the Macbook display.

**Comment by omarsonmarz** [comment]
Problem also occurs on Arc browser (Chromium-based), same model of MacBook.

**Comment by dsturnerville** [comment]
Also having the same issue on Microsoft Edge on MacOS
