### ISSUE TITLE
Security considerations

### ISSUE THREAD

**Issue by SarvagyaVaish** [SoFriendly/2fhey#25]
What were the security considerations kept in mind while creating this app? Does it access the internet and possibly leak codes to attackers?

**Comment by itsthisjustin** [comment]
The only access to the network it has is at launch it checks for an updated list of known sender formats from this github. You're more than welcome to review the code yourself though!

**Comment by SarvagyaVaish** [comment]
Gotcha! Thanks :) 
Can you also point me to the file with the network access, please?
