### ISSUE TITLE
Version number doesn't match dmg name

### ISSUE THREAD

**Issue by nihaals** [SoFriendly/2fhey#26]
The `2FHey1.0.3.dmg` file's app's `CFBundleShortVersionString` is 1.0.1.

**Comment by itsthisjustin** [comment]
Ha thanks for noticing this. I'm having some issues with the permission checking on the latest macOS so when that binary finally is fixed I'll update the short version in the code too.

**Comment by itsthisjustin** [comment]
Fixed this in the latest release!

**Comment by nihaals** [comment]
It looks like it now has 1.0.3 for the 1.0.4 release.

**Comment by itsthisjustin** [comment]
Alright should be actually fixed now. Uploaded a new version to Gumroad. Don't get how that happened. Thanks again.
