### ISSUE TITLE
"Copied to Clipboard" doesn't always show

### ISSUE THREAD

**Issue by nihaals** [SoFriendly/2fhey#27]
When I receive an actual verification code SMS, the "Copied to Clipboard" message doesn't show (but the code is still copied to the clipboard), but when I message myself (either with iMessage or SMS), receiving the message shows the popup.

I'm on macOS 13.3.0 and 2FHey 1.0.3.

**Comment by moonxkang** [comment]
might be a dumb question, but how do you know what version you have? i don't see anything in the app

**Comment by itsthisjustin** [comment]
You can right click get info on the app icon and it'll tell you in the Finder popup
