### ISSUE TITLE
Typo in opening popup

### ISSUE THREAD

**Issue by jelias** [SoFriendly/2fhey#3]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1644531/169404343-040d10dc-8ad0-4aee-99ef-8d7c79a23ff3.png">
"soounding" should be "sounding"

Only noticed since I thought it was stylistic as first ("soooorrrryyy" vibes). But might be good to fix considering you're asking for full disk permissions haha.

Cheers on the app!

**Comment by itsthisjustin** [comment]
Ha thanks! I'll fix this asap.
