### ISSUE TITLE
AMEX India - Instead of the one-time password, the amount is copied.

### ISSUE THREAD

**Issue by hdecoded** [SoFriendly/2fhey#31]
Message from AMEX India:

Your Amex SafeKey One-Time Password for INR 1234.00 is 672643. Valid for 10 mins for Card ending  xxxxx. Never share this password.

Instead of copying the actual one-time password (672643) in the message, the application copies the amount located immediately after "INR" i.e 1234.

Please let me know if you need any other details.

**Comment by itsthisjustin** [comment]
I cannot for the life of me get this one fixed. Apologies it's taken so long for me to get back to this. No matter what I put in there it always grabs that amount. I'm thinking maybe the app needs to prioritize customPatterns over known patterns for this to work?

**Comment by itsthisjustin** [comment]
This is fixed in the latest update! It does require that you download the updated version of the app though.

**Comment by hdecoded** [comment]
Thanks @itsthisjustin for the fix. Much Appreciated.
