### ISSUE TITLE
Proposal to use AI for parsing OTP

### ISSUE THREAD

**Issue by neo773** [SoFriendly/2fhey#39]
Hi,
I've been thinking about how we handle OTP parsing. Currently, we maintain so many regex patterns.
What if we leverage OpenAI's new function calls instead? 
This would eliminate maintaining the config all together.

Here's a sample snippet I wrote in TypeScript it's pretty accurate and parsed the most complex OTP on the 1st run.
Execution time averages at around 1.5s from my trial runs.

<img width="1496" alt="Screenshot 2023-10-10 at 10 11 13 PM" src="https://github.com/SoFriendly/2fhey/assets/62795688/c09e8954-2240-43bf-bdec-f86237ca3c80">

**Comment by itsthisjustin** [comment]
Oh that's very cool. Would probably be best people can put their own api key so it doesn't cost to run, but I'm not sure people would use it then. Thoughts?

**Comment by chrismessina** [comment]
Would be much better to run an LLM locally for that purpose if you were to head in that direction given that OTPs are a security method designed you ensure that you have control of a known device. If you send all your text messages to OpenAI, that's opening quite a few privacy and security surface areas.

Plus, do the regexes fail that often to warrant such a solution?

**Comment by itsthisjustin** [comment]
Yeah but local LLM sounds like way more processing than I want happening for such a silly little utility running in the background.

**Comment by chrismessina** [comment]
Understood, which brings me back to wondering whether an LLM is like bringing a Howitzer to a 2FA knife fight. 😉

**Comment by itsthisjustin** [comment]
General note here that the new updated logic SHOULD be much more reliable in detecting codes. I don't think we need this ticket anymore but please test and let me know!
