### ISSUE TITLE
Send desktop notification

### ISSUE THREAD

**Issue by shepherdjerred** [SoFriendly/2fhey#44]
Hello!

Thanks so much for making this app. I purchased it the moment I read the description.

I use the [Orion browser](https://kagi.com/orion/). 2fhey works great, but I don't see any type of notification whenever a 2FA code is copied to my clipboard.

It looks like there is _some_ popup based on the marketing material for this app, but it hasn't ever worked for me.

Would it be possible to send a desktop notification whenever a code is copied to the clipboard? I would find that immensely helpful!

**Comment by itsthisjustin** [comment]
That IS how it works. I need to build and publish the latest updates to this code which lets you position the notification where you want it. It also should fix an issue with certain browsers hiding the notification

**Comment by itsthisjustin** [comment]
@shepherdjerred  can you please test this before I send it out to others? In the dropdown in the menu bar you will find a notification position you can now select. https://files.sofriendly.com/uky23lc3

**Comment by shepherdjerred** [comment]
That seems to be working much better! Thank you for fixing this.
