### ISSUE TITLE
Does not work on Somona OS

### ISSUE THREAD

**Issue by davidkim0** [SoFriendly/2fhey#45]
Running Somona and using Chrome. Yes, I've followed the setup steps and retried multiple times.

**Comment by itsthisjustin** [comment]
What doesn't work? I'm also on Sonoma with Chrome and working fine.

**Comment by davidkim0** [comment]
Working fine now. I've closed the issue and updated my reddit comment.
    On Saturday, February 24, 2024 at 10:33:42 AM CST, Justin Mitchell ***@***.***> wrote:  
 
 


What doesn't work? I'm also on Sonoma with Chrome and working fine.
