### ISSUE TITLE
How to update to 1.1?

### ISSUE THREAD

**Issue by rubicon** [SoFriendly/2fhey#46]
I purchased your app (I love it), and my MacUpdater app shows me an update (v1.1).  How do I install that?  I've closed and opened the app and have yet to get a response, and I don't see an option in any of the dropdowns or dialog boxes.  Can you help point me in the right direction?

**Comment by itsthisjustin** [comment]
There isn't any auto updating feature in the app as it breaks some of the permissions we need. I'm still looking into it. In the meantime you can grab the latest from Gumroad. I also sent an email out to all buyers there with a link to the latest.

**Comment by rubicon** [comment]
Thanks for letting me know.  I'll look on Gumroad and/or look for your email.
