### ISSUE TITLE
Make Product > Test work right after cloning

### ISSUE THREAD

**Issue by ichoosetoaccept** [SoFriendly/2fhey#50]
I tried to get this to work locally but could not.

IMHO you should get the project in a state where I can successfully run the tests stored in /2fhey/2FHeyTests/TwoFHeyTests.swift right after cloning the repo locally and opening the .xcodeproj file in Xcode.

As it stands now I get this when trying to run the tests:
![CleanShot 2024-03-11 at 23 04 59@2x](https://github.com/SoFriendly/2fhey/assets/1242091/caabb606-fb82-4269-a198-21496d621cf6)

Xcode is also complaining about "No such module 'TwoFHey'" in the same file.

**Comment by itsthisjustin** [comment]
I think this is just an issue of the latest renaming operation I did. Should work if you just rename Two to 2.

**Comment by ichoosetoaccept** [comment]
> I think this is just an issue of the latest renaming operation I did. Should work if you just rename Two to 2.

Does this work for you, locally? If so, which "Two" did you change to a "2" to get tests to run? There are quite a few "TwoFHey"'s across the repo.

I'll be able to investigate myself later, but if you already got this to work, do let me know. Thanks!

**Comment by itsthisjustin** [comment]
Ok take a look now. I undid my changes from before. Swift doesn't like stuff to start with a number I guess.

**Comment by ichoosetoaccept** [comment]
That seems to have helped matters a bit but I still can't get the project to build successfully.
![CleanShot 2024-03-16 at 17 52 58@2x](https://github.com/SoFriendly/2fhey/assets/1242091/897bd2e7-5801-4ae0-a7c8-f6e2e7cc9f5f)
and
![CleanShot 2024-03-16 at 17 53 17@2x](https://github.com/SoFriendly/2fhey/assets/1242091/02bbcf37-51f9-4226-a220-c3036523a53f)
are my current issues.
TwoFHeyTests.swift imports the "module" TwoFHey but that module does not seem to exist in any package collection known to my Xcode.

Do you have the same issue with the TwoFHeyTests.swift file?
I'll deal with the account and signing cert issues once this import problem is solved.

Thanks!

**Comment by itsthisjustin** [comment]
Can you do a project clean and make sure the tests folder is in your workspace on the left?

**Comment by ichoosetoaccept** [comment]
Cleaning resolved the account and signing cert issues!

Now the only build-breaking issue remaining is with import TwoFHey:
![CleanShot 2024-03-16 at 19 08 28@2x](https://github.com/SoFriendly/2fhey/assets/1242091/68023a22-875e-4252-b299-e4b9a86f0de3)

The tests folder is there.

**Comment by itsthisjustin** [comment]
Thanks for your patience on this. This is now fixed.
