### ISSUE TITLE
Google (UK) OTA Failed. Vodafone UK (OTA) Failed.

### ISSUE THREAD

**Issue by zimbow555** [SoFriendly/2fhey#51]
So I installed the app, its authorised but doesnt work correctly.

1) GMAIL - OTA = Failed to capture code

2) Vodafone UK - OTA  = failed to capture code

3) Amazon UK - OTA = Worked (as expected).

So 2 failed. How can I get this software to work.

Diirge says on github, so guys please help?

**Comment by zimbow555** [comment]
Google  - failed
OTA Message:
G-004857 is your Google verification code.

Vodafone - failed
OTA Message:
Don't share this code with anyone. Fraudsters can use it to access your online account and place orders. The code is valid for 20 minutes. Your code is PKAGT.

Platform: Sonoma 14.4
2Fhey (last build, pushed to my email 11days ago, cant see build name.

**Comment by itsthisjustin** [comment]
Please quit and restart the app and test again now. There was a JSON parsing issue introduced by one of the older updates

**Comment by zimbow555** [comment]
Google now works - Gr8t, but Vodafone UK failed.
Vodafone OTA:
Don't share this code with anyone. Fraudsters can use it to access your online account and place orders. The code is valid for 20 minutes. Your code is 97UHA.

**Comment by itsthisjustin** [comment]
This is now fixed.
