### ISSUE TITLE
New version stayed in dock

### ISSUE THREAD

**Issue by sfdye** [SoFriendly/2fhey#52]
Shouldn't it be menu bar only?

**Comment by shubhamshah02** [comment]
Yes, I have the same issue. Please fix this!

**Comment by itsthisjustin** [comment]
Yeah so strange cause I didn't change anything related to this. I'll fix it shortly though.

**Comment by itsthisjustin** [comment]
Fixed. Will be uploading a build shortly.

**Comment by itsthisjustin** [comment]
Re-download from the same Gumroad email and you'll get the fix. Apologies.

**Comment by sfdye** [comment]
Confirm fixed for the docking issue
