### ISSUE TITLE
USAA 2FA Code returning wrong response

### ISSUE THREAD

**Issue by k10urzd** [SoFriendly/2fhey#53]
SMS comes from 868722, 2fhey replied with 'FRAUD'

USAA FRAUD PREVENTION ALERT: USAA will never contact you for this code, don't share it: ######. Call 800-531-8722 if you gave it to anyone. Reply HELP for help.

**Comment by itsthisjustin** [comment]
Fixed in upcoming update. Thanks for flagging

**Comment by itsthisjustin** [comment]
Re-download from the same Gumroad email and you'll get the fix. Apologies.
