### ISSUE TITLE
[Regression in v1.2] Dock Icon is no longer hidden

### ISSUE THREAD

**Issue by rommytowe** [SoFriendly/2fhey#57]
Previously, 2FHey ran solely in the menu bar, but in 1.2 the dock icon is also running (at least on my macOS 14.4). As all PMs do, I wish I could help instead of just filing an issue, but c'est la vie 🙃

**Comment by adamfeldman** [comment]
Please see https://github.com/SoFriendly/2fhey/issues/52#issuecomment-2005515462

> Re-download from the same Gumroad email and you'll get the fix.

**Comment by rommytowe** [comment]
> Please see [#52 (comment)](https://github.com/SoFriendly/2fhey/issues/52#issuecomment-2005515462)
> 
> > Re-download from the same Gumroad email and you'll get the fix.

Copy that; thanks @adamfeldman!
